# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2be9e8e6f9eec6b5cf878248a8fa71a7bfcc309d91f363366147f986a94d03be7f5a54a31dd0276039dac536a46dc44d84275a239f7caffa175e3ebec097d63d

test:
  secret_key_base: a74988c10a954e8dfb4a96349a4e4bdbd07c310bca70c4f7eaa2b06b29fc9ea1849b3826a7acb8391882abb92bcefacc55857a5b8dc24b1cd2a58794ebbaa382

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
